HomeWork16
JustShooter/It.Academy.LearnJava pull request #5
Opened 2022-01-01 20:37 UTC by JustShooter

Hope all good!

2022-01-01 20:38 UTC, JustShooter commented
![](https://github.trello.services/images/mini-trello-icon.png) [16 Практическая часть 28.12.2021](https://trello.com/c/zeZ8wzA2/508-16-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-28122021)

2022-01-02 19:32 UTC, JustShooter commented
Там в 3 задании можно ещё 3 компаратора допилить, что бы сортировать в обратном порядке. Я просто забыл изначально об этом...

2022-01-03 08:14 UTC, Vlasik-Henadzi requested changes

2022-01-03 08:14 UTC, Vlasik-Henadzi commented on src/HomeWork16/Task1/Model/NewProduct.java
> +public class NewProduct {
если делаешь неизменный класс,  то перед класса тоже final нужно ставить, чтобы наследников небыло

2022-01-05 23:42 UTC, merged