HomeWork17
JustShooter/It.Academy.LearnJava pull request #6
Opened 2022-01-02 19:25 UTC by JustShooter

Hope all good!

2022-01-02 19:26 UTC, JustShooter commented
![](https://github.trello.services/images/mini-trello-icon.png) [17 Практическая часть 30.12.2021](https://trello.com/c/rmRBBc2R/522-17-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-30122021)

2022-01-03 08:18 UTC, Vlasik-Henadzi commented on src/HomeWork17/Task47/Task47.java
> +        Pattern p = Pattern.compile("[A-Za-zА-Яа-я]{2,}"); // Слово должно содержать не менее 2 букв
в патернах есть сокрашенное название для слова как \d для цифр

2022-01-03 08:19 UTC, Vlasik-Henadzi requested changes

2022-01-03 08:19 UTC, Vlasik-Henadzi commented on src/HomeWork17/Task48/Task48.java
> +        Pattern p = Pattern.compile("\\d++");
патерн в константу

2022-01-05 23:48 UTC, merged